### ISSUE TITLE
Docker-compose 

### ISSUE THREAD

**Issue by Chomikmarkus** [arcaneiceman/Kraken#26]
Have error getting it up and running 
System ubuntu 20.04, 
root@ubuntu-s-1vcpu-2gb-fra1-01:/opt/kraken# docker-compose up
Creating minio    ... error
Creating postgres ...

ERROR: for minio  Cannot start service s3: error while creating mount source path '/opt/krCreating postgres ... done

ERROR: for s3  Cannot start service s3: error while creating mount source path '/opt/kraken/kraken-server/s3': mkdir /opt/kraken: read-only file system
ERROR: Encountered errors while bringing up the project.
root@ubuntu-s-1vcpu-2gb-fra1-01:/opt/kraken#

**Comment by arcaneiceman** [comment]
Hello! It seems youre trying to write to /opt/kraken . This happens in docker-compose when you create the minio container which creates a volume. Its trying to create the directory '/opt/kraken/kraken-server/s3' (which will serve as the persistent volume to minio) but it cant since your file system is read only, even to root.
 
To resolve this, ideally, place your docker-compose file in the home directory /home or /home/[your-user-name] and try again.
docker-compose should be able to deploy all containers there. Otherwise, you'll have to give write permissions to /opt/kraken path.

**Comment by arcaneiceman** [comment]
Please let me know if the resolution helped. If this is no longer an issue, I'll close the issue after a week from issue creation. Otherwise feel free to follow up! Thanks
